import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import NavBar from "@/components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <div className={styles.container}>
      

      <NavBar username="Test@gmail.com"/> 
      <Banner title="Clifford the red dog" subTitle="a very cute dog" imgUrl="/static/clifford.webp"/>
      {/* <Card/> */}


      </div>
      </>
  );
}
