import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Banner from "@/components/Banner";
import NavBar from "@/components/Navbar";
import Card from "@/components/Card";
import React from "react";
import SectionCard from "@/components/SectionCard";
import { getVideos } from "@/lib/videos";

export async function getServerSideProps(): Promise<{
  props: {
    disneyVideos: Video[];
    actionVideos: Video[];
    comedyVideos: Video[];
    cinemaVideos: Video[];
  };
}> {
  try {
    interface Video {
      title: string;
      url: string;
      id: string;
    }
    const disneyVideos: Video[] = await getVideos("Disney");
    const actionVideos: Video[] = await getVideos("Action");
    const comedyVideos: Video[] = await getVideos("Comedy");
    const cinemaVideos: Video[] = await getVideos("One Piece");
    return {
      props: {
        disneyVideos,
        actionVideos,
        comedyVideos,
        cinemaVideos,
      },
    };
  } catch (error) {
    console.error("Failed to fetch videos:", error);
    return {
      props: {
        disneyVideos: [],
        actionVideos: [],
        comedyVideos: [],
        cinemaVideos: [],
      },
    };
  }
}

interface Video {
  title: string;
  url: string;
  id: string;
}
interface HomeProps {
  disneyVideos: Video[];
  actionVideos: Video[];
  comedyVideos: Video[];
  cinemaVideos: Video[];
}

export default function Home({
  disneyVideos,
  actionVideos,
  comedyVideos,
  cinemaVideos,
}: HomeProps) {
  return (
    <>
      <Head>
        <title>Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <NavBar username="Test@gmail.com" />
        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCard title="Disney">
            {disneyVideos?.map((video: object, idx: number) => {
              return (
                <Card key={idx} imgUrl={video.imgUrl} size="large" id={idx} />
              );
            })}
          </SectionCard>

          <SectionCard title="Action">
            {actionVideos?.map((video: object, idx: number) => {
              return (
                <Card key={idx} imgUrl={video.imgUrl} size="small" id={idx} />
              );
            })}
          </SectionCard>
          <SectionCard title="Comedy">
            {comedyVideos?.map((video: object, idx: number) => {
              return (
                <Card key={idx} imgUrl={video.imgUrl} size="medium" id={idx} />
              );
            })}
          </SectionCard>
          <SectionCard title="Anime">
            {cinemaVideos?.map((video: object, idx: number) => {
              return (
                <Card key={idx} imgUrl={video.imgUrl} size="small" id={idx} />
              );
            })}
          </SectionCard>
        </div>
      </div>
    </>
  );
}
